const sampleEvents = [
  "Visionary Horizons: Exploring Tomorrow's Breakthroughs in Science & Tech",
  "AI Frontiers: Charting the Path to Intelligent Innovation",
  "Founder's Circle: A Night of Ideas & Impact",
  "Cloud Catalyst: Accelerate Your Journey to Scalable Success",
  "Innovators Unite: Pitch, Connect & Collaborate",
  "Ignite Minds: A Fireside Dialogue with Industry Leaders",
  "Tech Odyssey: Mapping the Next Era of Smart Solutions",
  "Startup Spark: Showcasing Bold Ideas & Bright Futures",
  "Beyond Boundaries: Unlocking Creativity in a Connected World",
  "Innovating Together: Building Smarter Cities for Tomorrow",
  "Voices of Change: Empowering Communities Through Technology",
  "Breaking Barriers: Women Leading in STEM",
  "The Future of Work: AI and Human Collaboration",
  "Green Horizons: Sustainable Solutions for a Better Planet",
  "Cultural Crossroads: Celebrating Diversity in a Global Age",
  "From Idea to Impact: Startup Journeys That Inspire",
  "Digital Wellness: Balancing Life in a Connected World",
  "Resilient Leadership: Thriving in Times of Uncertainty",
  "Creative Sparks: Unlocking Innovation Through Art and Design",
  "Next Gen Learning: Education in the Age of AI",
  "Health Redefined: Tech-Driven Breakthroughs in Medicine",
  "Global Voices: Storytelling for Social Impact",
  "Cyber Frontiers: Securing the Digital Future",
  "Beyond Boundaries: Collaboration Across Cultures",
  "Quantum Leap: The Next Revolution in Computing",
  "Data Democracy: Making Analytics Accessible to All",
  "Blockchain Beyond Crypto: Real-World Applications",
  "The Metaverse Economy: Opportunities and Challenges",
  "Remote Revolution: Redefining the Modern Workplace",
  "Fintech Forward: Transforming Financial Services",
  "EdTech Evolution: Learning in the Digital Age",
  "Climate Tech: Innovation for a Sustainable Future",
  "Biotech Breakthroughs: The Future of Healthcare",
  "Space Tech: Commercializing the Final Frontier",
  "Robotics Revolution: Automation in Everyday Life",
  "5G and Beyond: The Infrastructure of Tomorrow",
  "Privacy Matters: Data Protection in the Digital Era",
  "Inclusive Innovation: Technology for Everyone",
  "AgriTech Advances: Feeding the World with Technology"
];

export default sampleEvents;

